server:
  port: 8080 #Если 8080 занят — поставьте 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<segment>.*), /${segment}

        - id: hotel-service-route
          uri: lb://hotel-service
          predicates:
            - Path=/hotel/**
          filters:
            - RewritePath=/hotel/(?<segment>.*), /${segment}

        - id: booking-service-api-route
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - RewritePath=/api/booking/(?<segment>.*), /${segment}

        - id: hotel-service-api-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotel/**
          filters:
            - RewritePath=/api/hotel/(?<segment>.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
