server:
  port: 8080 #Если 8080 занят — поставьте 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # ТЕХНИЧЕСКИЕ: /booking/** и /hotel/**
        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<segment>.*), /${segment}

        - id: hotel-service-route
          uri: lb://hotel-service
          predicates:
            - Path=/hotel/**
          filters:
            - RewritePath=/hotel/(?<segment>.*), /${segment}

        # ПУБЛИЧНЫЕ API
        # Booking API: /api/booking/**
        - id: booking-service-api-route
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - RewritePath=/api/booking/(?<segment>.*), /${segment}

        # Hotel API: /api/hotels/**
        - id: hotel-service-hotels-api-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**

        # Hotel API: /api/rooms/**
        - id: hotel-service-rooms-api-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/rooms/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
