server:
  port: 8080 # или 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # =========================
        # Booking Service
        # =========================
        # Публичный API бронирований и пользователей
        # Gateway НЕ переписывает путь — сервисы работают сразу с /api/**
        - id: booking-service-api-route
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**,/api/bookings/**,/api/user/**

        # =========================
        # Hotel Service
        # =========================
        # Публичный API отелей и номеров
        # ВАЖНО:
        #   - публикуются ТОЛЬКО публичные endpoints
        #   - internal endpoints подтверждения / освобождения
        #     НЕ должны быть доступны через gateway
        - id: hotel-service-api-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**,/api/rooms,/api/rooms/recommend


# =========================
# Eureka
# =========================

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true


# =========================
# Management / Actuator
# =========================

management:
  endpoints:
    web:
      exposure:
        include: health,info
