server:
  port: 8080 #Если 8080 занят — поставьте 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # =========================
        # ТЕХНИЧЕСКИЕ: /booking/** и /hotel/**
        # =========================

        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<segment>.*), /${segment}

        - id: hotel-service-route
          uri: lb://hotel-service
          predicates:
            - Path=/hotel/**
          filters:
            - RewritePath=/hotel/(?<segment>.*), /${segment}

        # =========================
        # ПУБЛИЧНЫЕ API
        # =========================

        # Booking API: /api/booking/**  -> /{segment}
        - id: booking-service-api-booking-route
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - RewritePath=/api/booking/(?<segment>.*), /${segment}

        # Booking API: /api/bookings/** -> /{segment}
        # (история бронирований и т.п.)
        - id: booking-service-api-bookings-route
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - RewritePath=/api/bookings/(?<segment>.*), /${segment}

        # User API: /api/user/** -> /{segment}
        # (register/auth + позже admin CRUD)
        - id: booking-service-api-user-route
          uri: lb://booking-service
          predicates:
            - Path=/api/user/**
          # ВАЖНО: без RewritePath!
          # Пусть booking-service получит URL как есть: /api/user/register

        # Hotel API: /api/hotels/**
        - id: hotel-service-hotels-api-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**

        # Hotel API: /api/rooms/**
        - id: hotel-service-rooms-api-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/rooms/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
